"""empty message

Revision ID: 0225bf1f828c
Revises: b3a0a6eae36e
Create Date: 2025-07-08 15:39:47.283237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0225bf1f828c'
down_revision = 'b3a0a6eae36e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.alter_column('planet_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('spaceship_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('warrior_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.alter_column('warrior_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('spaceship_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('planet_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
