"""empty message

Revision ID: 68f695493cda
Revises: 0225bf1f828c
Create Date: 2025-07-08 15:42:18.187933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68f695493cda'
down_revision = '0225bf1f828c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.alter_column('planet_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('spaceship_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('warrior_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.alter_column('warrior_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('spaceship_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('planet_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
